Added Datadog blog tutorial
redis-developer/redis-developer.github.io pull request #169
Opened 2021-11-11 18:41 UTC by ajeetraina

2021-11-14 20:34 UTC, simonprickett requested changes
Left some minor review comments / suggestions and questions about whether configuration values begin `redisenterprise.` or `redis_enterprise.` (I'm not sure but there's a little bit of a mix of both here).

2021-11-14 20:34 UTC, simonprickett commented on docusaurus.config.js
> +        title: 'Principle Field Engineer at Redis',
```suggestion
        title: 'Principal Field Engineer at Redis',
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +| Latency    | Elapsed time it takes for an operation | Average write latency should not exceed 1 millisecond | redis_enterprise.avg_latency |
The other two SLIs are `redisenterprise.`, this one is `redis_enterprise.` - is the `_` correct here, just asking as it seems inconsistent with the other two names, but may be how it is in the product, I don't know.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +##### redis_enterprise.avg_latency (unit: microseconds)
Note sure whether these metric names have `_` in `redis_enterprise` or not, but usage of it should be consistent with the table above so that al mentions of the metric use the same spelling.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +##### redis_enterprise.memory_usage_percent (unit: percentage)
See earlier question about whether `_` is required here or not.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +#####  redis_enterprise.cache_hit_rate (unit: percent)
See earlier comments about whether `_` is required here or not, I don't know - just checking for consistency.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +##### redis_enterprise.evicted_objects (unit: count)
See previous comments re `_`.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +##### redis_enterprise.evicted_objects (unit: count)
Same for other uses of `redis_enterprise.` from here onwards.

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +The count of current client connections to the database.
```suggestion
The number of current client connections to the database.
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +You can access the complete list of metrics [under this link.](https://github.com/DataDog/integrations-extras/blob/master/redisenterprise/metadata.csv)
```suggestion
You can access the complete list of metrics [here](https://github.com/DataDog/integrations-extras/blob/master/redisenterprise/metadata.csv).
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +Follow the below steps to set up the Datadog agent to monitor your Redis Enterprise cluster, as well as database metrics:
```suggestion
Follow the steps below to set up the Datadog agent to monitor your Redis Enterprise cluster, as well as database metrics:
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +#### Prerequisite:
```suggestion
#### Prerequisites:
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +- Setup a Read-only user account by logging into your Redis Enterprise instance and visiting “Access Control” section
```suggestion
- Setup a Read-only user account by logging into your Redis Enterprise instance and visiting the “Access Control” section
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +Before we jump into the installation, let’s look at the various modes that you can run the datadog agent in:
```suggestion
Before we jump into the installation, let’s look at the various modes that you can run the Datadog agent in:
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +Run the following command to install the integration wheel with the Agent. Replace the integration version with 1.0.1.
"Run the following command" - do you need to add the command here?

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +The below minimal configuration should be added to the Enterprise Master node.
```suggestion
The following minimal configuration should be added to the Enterprise Master node.
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +Similarly, you need to add the below content into the configuration file for the Enterprise Follower:
```suggestion
Similarly, you need to add the edit the configuration file for the Enterprise Follower to add the following:
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +The below configuration should be added to the Monitor node
```suggestion
The following configuration should be added to the Monitor node
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +### Step 4. Restart the datadog Agent service
```suggestion
### Step 4. Restart the Datadog Agent service
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +Find the Redis Enterprise Integration under the Integration Menu
```suggestion
Find the Redis Enterprise Integration under the Integration Menu:
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +The below snippet of the result shows that Redis Enterprise integrator is working without any issue.
```suggestion
Running the `datadog-agent` command shows that the Redis Enterprise integration is working correctly.
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +- Write objects only, no reads
```suggestion
- Write objects only, no reads.
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +- Each object is 500 bytes
```suggestion
- Each object is 500 bytes.
```

2021-11-14 20:34 UTC, simonprickett commented on docs/explore/datadog/index-datadog.mdx
> +- Each object has random data in the value
```suggestion
- Each object has random data in the value.
```

2021-11-15 04:38 UTC, ajeetraina commented on docs/explore/datadog/index-datadog.mdx
> +| Latency    | Elapsed time it takes for an operation | Average write latency should not exceed 1 millisecond | redis_enterprise.avg_latency |
Good catch. The metrics name starts with redisenterprise.... Fixed it.

2021-11-15 04:40 UTC, ajeetraina commented
Thanks @simonprickett for the review. I have made the necessary changes.

2021-11-15 11:52 UTC, ajeetraina commented
Hi @simonprickett I hope I have scanned through all the reviewed comments. If I missed any, do let me know.
Thanks again for the review.

2021-11-15 12:29 UTC, simonprickett reviewed
Have the `redisenterprise.` vs `redis_enterprise.` configuration value questions been resolved here?  I've also flagged changing Chris' job title from "Principle" to "Principal".

2021-11-15 12:29 UTC, simonprickett commented on docusaurus.config.js
> +        title: 'Principle Field Engineer at Redis',
```suggestion
        title: 'Principal Field Engineer at Redis',
```

Correcting Chris' job title.

2021-11-15 16:31 UTC, simonprickett approved these changes
@ajeetraina approved - I will leave this for you to merge whenever you want to launch this article.

2021-11-15 16:59 UTC, merged