Updated Node intro for node-redis 4 and to make node-redis primary choice.
redis-developer/redis-developer.github.io pull request #184
Opened 2021-11-25 17:41 UTC by simonprickett

This updates node-redis examples for v 4 and also changes the ioredis example to be the same as the node-redis one... using scan behavior on a sorted set in both clients.

Closes #183

2021-11-30 11:14 UTC, simonprickett commented
@ajeetraina @guyroyse could you check this over please.  Thanks.

2021-11-30 19:07 UTC, guyroyse requested changes

2021-11-30 19:07 UTC, guyroyse commented on docs/develop/node/gettingstarted/index-gettingstarted.mdx
> +Redis has two primary Node.js clients which are [node-redis](https://github.com/redis/node-redis) and [ioredis](https://github.com/luin/ioredis). Both are available through npm. We generally suggest
Oxford comma at the end. I would also change the end to say: "it has great support for Redis modules, is easily extended, and is widely used."

2021-12-03 18:14 UTC, guyroyse approved these changes

2021-12-03 18:18 UTC, merged