Redis OM Spring Tutorial #1
redis-developer/redis-developer.github.io pull request #192
Opened 2021-11-30 19:54 UTC by bsbodden

This is tutorial #1 for Redis OM Spring, covering JSON object mapping and search.

2021-12-03 14:33 UTC, simonprickett approved these changes
@bsbodden left some suggestions inc a couple of missing URLs, otherwise good to go!

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +* `@Bloom` annotation to determine very fast, with and with high degree of certainty, whether a value is in a collection.
```suggestion
* `@Bloom` annotation to determine very fast, with and with high degree of certainty, whether a value is in a collection
```

Removed period for consistency.

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +The JSON format has become ubiquiouts as a data exchange format as well as a storage format,
```suggestion
The JSON format has become ubiquitous as a data exchange format as well as a storage format,
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +a dataformat eliminates the rigidity of relational database schemas, allow applications to
```suggestion
a data format eliminates the rigidity of relational database schemas, allow applications to
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +You will build an application that stores `Company` POJOs (Plain Old Java Objects) a JSON documents in Redis.
```suggestion
You will build an application that stores `Company` POJOs (Plain Old Java Objects) as JSON documents in Redis.
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +Redis OM Spring relies on the power of the [RediSearch][redisearch-url] and [RedisJSON][redis-json-url] modules.
```suggestion
Redis OM Spring relies on the power of the [RediSearch][https://redisearch.io/] and [RedisJSON][https://redisjson.io] modules.
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +The docker compose YAML file below can get started quickly. You can place at the root folder of your project and name it
```suggestion
The Docker Compose YAML file below can get you started quickly. You can place it in the root folder of your project and name it `docker-compose.yml`:
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +To launch the docker compose application, on the command line (or via Docker Desktop), clone this repository and run (from the root folder):
```suggestion
To launch the Docker Compose application, on the command line (or via Docker Desktop), clone this repository and run (from the root folder):
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +for working with Company persistence, including methods for saving, deleting, and finding Company entities.
```suggestion
for working with `Company` persistence, including methods for saving, deleting, and finding `Company` entities.
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +If every goes as expected, you should see the familiar Spring Boot banner fly by:
```suggestion
If everything goes as expected, you should see the familiar Spring Boot banner fly by:
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +With our new gained understanding of how ROMS serialized our `Company` POJOs, let's move on to expanding the powers of
```suggestion
With our newly gained understanding of how ROMS serialized our `Company` POJOs, let's move on to expanding the powers of
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +With our new gained understanding of how ROMS serialized our `Company` POJOs, let's move on to expanding the powers of
```suggestion
With our newly gained understanding of how ROMS serialized our `Company` POJOs, let's move on to expanding the powers of
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +### Create Simple Dynamic Queries
```suggestion
### Creating Simple Dynamic Queries
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +In our controller, we include our `CompanyRepository` and create simple method to respond to a GET request at
```suggestion
In our controller, we include our `CompanyRepository` and create a simple method to respond to a GET request at
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +Let's test the endpoint using CURL and passing the exact company name `Redis`:
```suggestion
Let's test the endpoint using CURL by passing it the exact company name `Redis`:
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +Let's add a testing end point to our controller for our Geo query:
```suggestion
Let's add a test endpoint to our controller for our Geo query:
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/rate-limiting/getting-started/getting-started.mdx
>  ## Further Readings
```suggestion
## Further Reading
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring-json.mdx
> +---
```suggestion
authors: [bsb]
---
```

2021-12-03 14:33 UTC, simonprickett commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +---
```suggestion
authors: [bsb]
---
```

2021-12-03 18:45 UTC, guyroyse requested changes

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> + your language/platform of choice. We currently cater to the Node, Python, .Net and Spring communities.
stray space

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +The Redis OM family of projects aim is to provide high-level abstractions idiomatically implemented for
"aim" feels weird here. "The Redis OM family of projects aim to provide" or "The aim of the Reds OM family of projects is to provide".

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> + your language/platform of choice. We currently cater to the Node, Python, .Net and Spring communities.
Also, I think .NET is capitalized.

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> + your language/platform of choice. We currently cater to the Node, Python, .Net and Spring communities.
And Node.js is always written Node.js but spoken as Node. From their style guide.

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +powerful Spring Data Redis (SDR) framework.
"powerful" is used twice. Maybe use something like "capable" or something for one of them.

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +* Enhances SDR's `@RedisHash` via `@EnableRedisEnhancedRepositories` to:
The rest of the items in the list are nouns, this should be a noun too. Maybe "Enhancements to SDR's..."

2021-12-03 18:45 UTC, guyroyse commented on docs/develop/java/spring/redis-om/index-redis-om-spring.mdx
> +* `@Bloom` annotation to determine very fast, with and with high degree of certainty, whether a value is in a collection
determine very quickly... or fastly... or rapidly. Adverb instead of an adjective.

2021-12-03 20:08 UTC, guyroyse approved these changes

2021-12-07 18:27 UTC, banker commented
@guyroyse @simonprickett Can we merge and deploy this?

2021-12-07 18:28 UTC, merged

2021-12-07 18:29 UTC, simonprickett commented
@banker done - it will auto deploy once the GH actions scripts are finished.