Adds "Getting started with Redis Functions" tutorial
redis-developer/redis-developer.github.io pull request #330
Opened 2022-05-06 19:44 UTC by elena-kolevska

2022-05-12 09:59 UTC, simonprickett approved these changes
Left a couple of minor suggestions.

2022-05-12 09:59 UTC, simonprickett commented on docs/create/redis-functions/index-redis-functions.mdx
> +A common pain point for developers is to maintain a consistent view of  data entities through a logical schema. Redis Functions are ideally suited for solving this problem and in this tutorial we wil
```suggestion
A common pain point for developers is to maintain a consistent view of data entities through a logical schema. Redis Functions are ideally suited for solving this problem and in this tutorial we will demonstrate just that - we’ll create a library with two functions; the first one will make sure that we can automatically  set  `_created_at` and `_updated_at`  timestamps for hash keys and the second one will simply update the `_updated_at` timestamp without changing the other elements, simulating the “touch” Unix function. Let's go!
```

2022-05-12 09:59 UTC, simonprickett commented on docs/create/redis-functions/index-redis-functions.mdx
> +One of the basic rules of software development is that you can not rely on user input, so let’s make sure we don’t do that. If a user creates a string named `my_string` and tries to run the touch fun
```suggestion
One of the basic rules of software development is that you cannot rely on user input, so let’s make sure we don’t do that. If a user creates a string named `my_string` and tries to run the touch function on it they will get an error:
```

2022-05-12 19:52 UTC, bsbodden requested changes
This is great. I only added a few Oxford commas out of habit. The only thing that I was wondering is if there is anything that can be shown with Insight for this? I find Screenshots help break text and code visually. For an easier read.

2022-05-12 19:52 UTC, bsbodden commented on docs/create/redis-functions/index-redis-functions.mdx
> +The most impactful addition to Redis version 7.0 is **Redis Functions** - a new programmability option, improving on scripts by **adding modularity, reusability and better overall developer experienc
```suggestion
The most impactful addition to Redis version 7.0 is **Redis Functions** - a new programmability option, improving on scripts by **adding modularity, reusability, and better overall developer experience**. 
```

2022-05-12 19:52 UTC, bsbodden commented on docs/create/redis-functions/index-redis-functions.mdx
> +Redis has the capability of supporting multiple execution engines so in one of the future releases we’ll be able to write Redis Functions in Lua, Javascript and more languages, but at the moment (Red
```suggestion
Redis has the capability of supporting multiple execution engines so in one of the future releases we’ll be able to write Redis Functions in Lua, Javascript, and more languages, but at the moment (Redis v7.0) the only supported language is Lua.
```

2022-05-12 19:52 UTC, bsbodden commented on docs/create/redis-functions/index-redis-functions.mdx
> +A common pain point for developers is to maintain a consistent view of data entities through a logical schema. Redis Functions are ideally suited for solving this problem and in this tutorial we will
```suggestion
A common pain point for developers is to maintain a consistent view of data entities through a logical schema. Redis Functions are ideally suited for solving this problem and in this tutorial, we will demonstrate just that - we’ll create a library with two functions; the first one will make sure that we can automatically set  `_created_at` and `_updated_at`  timestamps for hash keys and the second one will simply update the `_updated_at` timestamp without changing the other elements, simulating the “touch” Unix function. Let's go!
```

2022-05-12 19:52 UTC, bsbodden commented on docs/create/redis-functions/index-redis-functions.mdx
> +Finally this will give us the expected result:
```suggestion
Finally, this will give us the expected result:
```

2022-05-13 09:28 UTC, elena-kolevska commented
@bsbodden Yeah, I know it's a lot of text and code, but there's nothing really meaningful to show with RedisInsight. maybe I could add some other (not totally related) images, but I don't know if they would make sense in a tutorial, as much as they do in a blog. Let me know if you have any other ideas?

2022-05-13 14:54 UTC, merged