adds this weeks schedule
redis-developer/redis-developer.github.io pull request #541
Opened 2023-02-06 17:49 UTC by justincastilla

2023-02-06 18:09 UTC, simonprickett requested changes

2023-02-06 18:09 UTC, simonprickett commented on docs/get-involved/redis-live/index-redis-live.mdx
> +| Thursday  | 10:30 AM UTC | [Simon Prickett][simon]                                                                               | [Simon's Things on Thursdays: New Project][twitch]               |
Don't need to set a title for my recurring one, just this week.

2023-02-06 20:31 UTC, savynorem approved these changes

2023-02-07 15:41 UTC, simonprickett approved these changes

2023-02-07 15:41 UTC, merged