article series: rate limiting in Spring Boot
redis-developer/redis-developer.github.io pull request #96
Opened 2021-09-10 05:05 UTC by bsbodden

In this series of mini-tutorials, we'll explore several approaches to implement rate-limiting in Spring applications using Redis. We’ll start with the most basic of Redis recipes and we’ll slowly increase the complexity of our implementations.

2021-09-10 14:36 UTC, slorello89 requested changes
Couple minor suggestions

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive-gears.mdx
> +4. If the quota hasn't been exceeded, perform the `INCR`/`EXPIRE` commands in a transactions (`with atomic():`)
```suggestion
4. If the quota hasn't been exceeded, perform the `INCR`/`EXPIRE` commands in a `with atomic():` block to ensure atomicity.
```

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive-gears.mdx
> +@PostConstruct
This code comes up really bunched up in docasaurus, it could use some spacing and some line separation to make it a bit more readable

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive-gears.mdx
> +The complete code for this implementation is under the branch [`with_gears`](https://github.com/redis-developer/fixed-window-rate-limiter/tree/with_gears).
Maybe put another header above this for Resources, along with a link to RedisGears' OSS page

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive.mdx
> +to happen atomically or not at all. Given that [`a Reactive API and Redis Transactions (MULTI/EXEC) are not compatible paradigms`](https://stackoverflow.com/questions/56647972/how-do-i-use-transactio
```suggestion
to happen atomically or not at all. Given that [a Reactive API and Redis Transactions (MULTI/EXEC) are not compatible paradigms](https://stackoverflow.com/questions/56647972/how-do-i-use-transactions-in-spring-data-redis-reactive), which boils down to "you cannot listen to a command that is going to be executed in the future" in a chain of reactive commands
```

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive.mdx
> +   - Is greater than or equal to the max quota we deny the request with a 409 response.
```suggestion
   - Is greater than or equal to the max quota we deny the request with a 429 response.
```

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive.mdx
> +You can find this example on the main branch at [https://github.com/redis-developer/fixed-window-rate-limiter](https://github.com/redis-developer/fixed-window-rate-limiter)
```suggestion
## Resources

* You can find this example on the main branch in the [fixed-window-rate-limiter](https://github.com/redis-developer/fixed-window-rate-limiter) repo.
```

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window.mdx
> +Ok, now that we know the basic recipe, let's implement it in [Spring](/develop/java/spring/rate-limiting/fixed-window/reactive)
This is probably superfolous as the next page button on the bottom is the same page :)

2021-09-10 14:36 UTC, slorello89 commented on docs/develop/java/spring/rate-limiting/index-rate-limiting.mdx
> +Now, let’s get started with our first implementation; the simple [“Fixed Window” implementation](/develop/java/spring/rate-limiting/fixed-window).
same thing here - there's buttons on the bottom :) unless it's an accessibility concern I'd say this isn't needed.

2021-09-12 14:55 UTC, bsbodden commented on docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive-gears.mdx
> +docker run -p 6379:6379 redislabs/redisgears:latest
Yeah, I've been defaulting to giving readers the mod one, since it might entice them to play with the other modules.

2021-09-20 07:47 UTC, merged

2021-09-20 10:21 UTC, ajeetraina commented
@bsbodden Can you structure the Spring Boot and Redis in the below manner:

```
ajeetraina@Ajeets-MacBook-Pro spring % tree
.
├── getting-started.mdx
├── index-spring.mdx
├── rate-limiting
│   ├── fixed-window
│   │   ├── images
│   │   │   └── start-spring-io-01.png
│   │   ├── index-fixed-window-reactive-gears.mdx
│   │   ├── index-fixed-window-reactive-lua.mdx
│   │   ├── index-fixed-window-reactive.mdx
│   │   └── index-fixed-window.mdx
│   ├── getting-started
│   │   └── getting-started.mdx
│   └── index-ratelimiting.mdx
└── redis-and-spring-course
    ├── index-redis-and-spring-course.mdx
    ├── lesson_1
    │   └── index-lesson_1.mdx
    ├── lesson_2
    │   └── index-lesson_2.mdx
    ├── lesson_3
    │   ├── images
    │   │   └── user-role-uml.png
    │   └── index-lesson_3.mdx
    ├── lesson_4
    │   └── index-lesson_4.mdx
    ├── lesson_5
    │   ├── images
    │   │   └── books_categories_ratings.png
    │   └── index-lesson_5.mdx
    ├── lesson_6
    │   ├── images
    │   │   └── carts_and_cartitems.png
    │   └── index-lesson_6.mdx
    ├── lesson_7
    │   └── index-lesson_7.mdx
    ├── lesson_8
    │   ├── images
    │   │   ├── redis-insight-query-graph.png
    │   │   ├── redis-insight-query-table.png
    │   │   └── redis-insight.png
    │   └── index-lesson_8.mdx
    └── lesson_9
        ├── images
        │   ├── image1.png
        │   └── image2.png
        └── index-lesson_9.mdx

19 directories, 27 files
```

2021-09-20 10:24 UTC, ajeetraina commented
I have pushed the following change <img width="1769" alt="Screen Shot 2021-09-20 at 3 53 51 PM" src="https://user-images.githubusercontent.com/313480/133987674-d16fec84-50bf-46ab-a5b0-3778a498dc79.png">